@startuml
class FlaskApp {
  - app: Flask
  - csv_file_path: str
  - current_image_index: int
  + next_image(): JSON
  + submit(): JSON
}

class Image {
  - id: int
  - source: str
  + get_id(): int
  + get_source(): str
}

FlaskApp -- Image : contains





class FileManager {
  + generate_csv(image_folder: str, csv_file_path: str): void
}

class CSVWriter {
  - csv_file: File
  - fieldnames: List[str]
  + __init__(csv_file_path: str, fieldnames: List[str])
  + write_header(): void
  + write_row(data: Dict[str, str]): void
}

class ImageData {
  - id_camera: str
  - id_img: str
  - source_img: str
  - text: str
  + __init__(id_camera: str, id_img: str, source_img: str, text: str)
}

FileManager --> CSVWriter : uses
FileManager --> ImageData : uses
@enduml
